# Numpy Notes

In [2]:
import numpy as np
import pandas as pd

## np array shape

In [3]:
A3 = np.array([1, 2, 3])
A1x3 = np.array([[1, 2, 3]])
print(A3.shape)
print(A1x3.shape)

(3,)
(1, 3)


In [4]:
# a is a rank 1 array
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))
print(np.dot(a.T, a))
a = a.reshape((5, 1))
print(a)
print()

# A is a column vector (5x1)
A = np.random.randn(5, 1)
print(A)
print(A.shape)
# A.T is a row vector (1x5)
print(A.T)
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[ 0.66103022  0.22541012  0.8379178  -2.04928652 -0.37734185]
(5,)
[ 0.66103022  0.22541012  0.8379178  -2.04928652 -0.37734185]
5.531839015089236
5.531839015089236
[[ 0.66103022]
 [ 0.22541012]
 [ 0.8379178 ]
 [-2.04928652]
 [-0.37734185]]

[[-1.23218952]
 [-1.12697403]
 [-1.09945813]
 [-2.06286743]
 [ 1.72354397]]
(5, 1)
[[-1.23218952 -1.12697403 -1.09945813 -2.06286743  1.72354397]]
[[ 1.51829102  1.3886456   1.35474079  2.54184363 -2.12373282]
 [ 1.3886456   1.27007047  1.23906077  2.32479803 -1.9423893 ]
 [ 1.35474079  1.23906077  1.20880819  2.26803637 -1.89496444]
 [ 2.54184363  2.32479803  2.26803637  4.25542203 -3.55544272]
 [-2.12373282 -1.9423893  -1.89496444 -3.55544272  2.97060383]]
[[11.22319553]]


In [6]:
a = np.random.randn(2,3,4)
print(a)
print(a.shape)

b = a.reshape(a.shape[0] * a.shape[1], a.shape[2])
print(b)
print(b.shape)

c = a.reshape(a.shape[0] * a.shape[1] * a.shape[2], 1)
print(c.shape)
print(c)

[[[ 1.06117804 -0.04162394  0.68131923 -0.57639256]
  [-0.49424923  0.69642398 -1.0577489  -1.06852531]
  [ 0.88058769 -1.32892988 -0.5853251   1.50214215]]

 [[ 0.65613505 -0.83777504 -0.97847071 -0.70270119]
  [-1.18214407  3.09882198 -0.16451145  0.99396859]
  [-1.81970381 -0.23305591 -1.85155983  0.05943543]]]
(2, 3, 4)
[[ 1.06117804 -0.04162394  0.68131923 -0.57639256]
 [-0.49424923  0.69642398 -1.0577489  -1.06852531]
 [ 0.88058769 -1.32892988 -0.5853251   1.50214215]
 [ 0.65613505 -0.83777504 -0.97847071 -0.70270119]
 [-1.18214407  3.09882198 -0.16451145  0.99396859]
 [-1.81970381 -0.23305591 -1.85155983  0.05943543]]
(6, 4)
(24, 1)
[[ 1.06117804]
 [-0.04162394]
 [ 0.68131923]
 [-0.57639256]
 [-0.49424923]
 [ 0.69642398]
 [-1.0577489 ]
 [-1.06852531]
 [ 0.88058769]
 [-1.32892988]
 [-0.5853251 ]
 [ 1.50214215]
 [ 0.65613505]
 [-0.83777504]
 [-0.97847071]
 [-0.70270119]
 [-1.18214407]
 [ 3.09882198]
 [-0.16451145]
 [ 0.99396859]
 [-1.81970381]
 [-0.23305591]
 [-1.85155983]
 [ 0.05

## eye and identity matrix

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Load txt data

In [10]:
data = np.loadtxt("ex1data1.txt",delimiter=',')

OSError: ex1data1.txt not found.

In [ ]:
data[:5]

In [ ]:
X = data[:, 0]
y = data[:, 1]

In [ ]:
X[:5], y[:5]

In [ ]:
m = len(X)
m

# Binding arrays

## Bind two or more 1-dimentional arrays as a matrix

In [ ]:
a = np.array([1, 2, 3])
b = np.ones(3)

In [ ]:
print(a.shape)
a

In [ ]:
print(b.shape)
b

In [ ]:
c = np.zeros(3)
m = np.column_stack((c, b, a))

In [ ]:
print(m.shape)
m

In [ ]:
np.dstack((c, b, a))

In [ ]:
np.vstack((c,b,a))

In [ ]:
np.stack((c, b, a))

In [ ]:
np.hstack((c, b, a))

In [ ]:
np.concatenate((c, b, a))

In [ ]:
np.append(b, a)

In [ ]:
np.append(b, a, axis=0)

## Reshape and flatten matrices

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a

In [ ]:
a.flatten('C')

In [ ]:
a.flatten('F')

In [ ]:
a.flatten('A')

In [ ]:
a.flatten('K')

In [ ]:
a.flatten()

A3x2 B2x1

In [ ]:
A = np.array([[1,2], [3,4], [5,6]])
A

In [ ]:
Bm = np.array([[1], [2]])
print(Bm.shape)
Bm

In [ ]:
Bv = np.array([1, 2])
print(Bv.shape)
Bv

In [ ]:
np.dot(A, Bm)

In [ ]:
np.dot(A, Bv)

## Sum/Addition

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)

In [ ]:
print(A.sum())       # sum all the elements
print(A.sum(axis=0)) # sum rows
print(A.sum(axis=1)) # sum columns

In [11]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4]])

print(a.shape)
print(b.shape)

sum_a = np.sum(a)
sum_b = np.sum(b)
print(sum_a.shape)
print(sum_b.shape)

sum_a_keep = np.sum(a, keepdims=True)
sum_b_keep = np.sum(b, keepdims=True)
print(sum_a_keep.shape)
print(sum_b_keep.shape)

(4,)
(1, 4)
()
()
(1,)
(1, 1)


In [ ]:
print(A + 100)
print()
B = np.array([[100, 200, 300]])
print(A + B)

## Vectorization vs for-loop

In [ ]:
import time

# w and x are 1 million array
w = np.random.rand(1000000)
x = np.random.rand(1000000)

tic = time.time()
c = np.dot(w, x)
toc = time.time()
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    c += w[i] * x[i]
toc = time.time()
print("for-loop version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    pass
toc = time.time()
print("for-loop pass version: " + str(1000*(toc-tic)) + "ms")
print(c)
