# Numpy Notes

In [24]:
import numpy as np
import pandas as pd

## np array shape

In [25]:
A3 = np.array([1, 2, 3])
A1x3 = np.array([[1, 2, 3]])
print(A3.shape)
print(A1x3.shape)

(3,)
(1, 3)


In [26]:
# a is a rank 1 array
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))
print(np.dot(a.T, a))
a = a.reshape((5, 1))
print(a)
print()

# A is a column vector (5x1)
A = np.random.randn(5, 1)
print(A)
print(A.shape)
# A.T is a row vector (1x5)
print(A.T)
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[ 2.14781124 -0.17314947 -1.00708862 -0.25458453 -0.56336505]
(5,)
[ 2.14781124 -0.17314947 -1.00708862 -0.25458453 -0.56336505]
6.039494810821523
6.039494810821523
[[ 2.14781124]
 [-0.17314947]
 [-1.00708862]
 [-0.25458453]
 [-0.56336505]]

[[ 0.69572502]
 [ 0.12944343]
 [ 0.4599395 ]
 [ 0.86507704]
 [-0.6881499 ]]
(5, 1)
[[ 0.69572502  0.12944343  0.4599395   0.86507704 -0.6881499 ]]
[[ 0.48403331  0.09005704  0.31999142  0.60185574 -0.47876311]
 [ 0.09005704  0.0167556   0.05953615  0.11197854 -0.08907649]
 [ 0.31999142  0.05953615  0.21154434  0.3978831  -0.31650732]
 [ 0.60185574  0.11197854  0.3978831   0.74835828 -0.59530268]
 [-0.47876311 -0.08907649 -0.31650732 -0.59530268  0.47355029]]
[[1.93424182]]


Reshape the training and test data sets so that images of size (num_px, num_px, 3) are flattened into single vectors of shape (num_px  ∗∗  num_px  ∗∗ 3, 1).

A trick when you want to flatten a matrix X of shape (a,b,c,d) to a matrix X_flatten of shape (b ∗∗ c ∗∗ d, a) is to use:

X_flatten = X.reshape(X.shape[0], -1).T      # X.T is the transpose of X

In [27]:
a = np.random.randn(2,3,4)
print(a)
print(a.shape)

b = a.reshape((a.shape[0] * a.shape[1], a.shape[2]))
print(b)
print(b.shape)

c = a.reshape((a.shape[0] * a.shape[1] * a.shape[2], 1))
print(c.shape)
print(c)

[[[ 1.10213437e+00 -5.77671244e-01  2.15238386e+00  5.94397031e-01]
  [-1.01971191e-03 -1.60856509e+00 -1.17987057e+00  1.47613056e+00]
  [ 9.10192870e-01  3.17824336e-01  4.57557025e-01 -6.49679960e-01]]

 [[ 2.72823397e-01 -1.34530009e+00 -8.07962124e-01 -5.13845323e-01]
  [-1.04741566e+00 -4.45306829e-01 -5.33580353e-01 -1.23559309e+00]
  [ 7.50514182e-01  1.27315836e+00  8.58702771e-01  1.76627307e+00]]]
(2, 3, 4)
[[ 1.10213437e+00 -5.77671244e-01  2.15238386e+00  5.94397031e-01]
 [-1.01971191e-03 -1.60856509e+00 -1.17987057e+00  1.47613056e+00]
 [ 9.10192870e-01  3.17824336e-01  4.57557025e-01 -6.49679960e-01]
 [ 2.72823397e-01 -1.34530009e+00 -8.07962124e-01 -5.13845323e-01]
 [-1.04741566e+00 -4.45306829e-01 -5.33580353e-01 -1.23559309e+00]
 [ 7.50514182e-01  1.27315836e+00  8.58702771e-01  1.76627307e+00]]
(6, 4)
(24, 1)
[[ 1.10213437e+00]
 [-5.77671244e-01]
 [ 2.15238386e+00]
 [ 5.94397031e-01]
 [-1.01971191e-03]
 [-1.60856509e+00]
 [-1.17987057e+00]
 [ 1.47613056e+00]
 [ 9.101

## eye and identity matrix

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [30]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [31]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Load txt data

In [33]:
data = np.loadtxt("ex1data1.txt",delimiter=',')

In [34]:
data[:5]

NameError: name 'data' is not defined

In [ ]:
X = data[:, 0]
y = data[:, 1]

In [ ]:
X[:5], y[:5]

In [ ]:
m = len(X)
m

# Binding arrays

## Bind two or more 1-dimentional arrays as a matrix

In [ ]:
a = np.array([1, 2, 3])
b = np.ones(3)

In [ ]:
print(a.shape)
a

In [ ]:
print(b.shape)
b

In [ ]:
c = np.zeros(3)
m = np.column_stack((c, b, a))

In [ ]:
print(m.shape)
m

In [ ]:
np.dstack((c, b, a))

In [ ]:
np.vstack((c,b,a))

In [ ]:
np.stack((c, b, a))

In [ ]:
np.hstack((c, b, a))

In [ ]:
np.concatenate((c, b, a))

In [ ]:
np.append(b, a)

In [ ]:
np.append(b, a, axis=0)

## Reshape and flatten matrices

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a

In [ ]:
a.flatten('C')

In [ ]:
a.flatten('F')

In [ ]:
a.flatten('A')

In [ ]:
a.flatten('K')

In [ ]:
a.flatten()

A3x2 B2x1

In [ ]:
A = np.array([[1,2], [3,4], [5,6]])
A

In [ ]:
Bm = np.array([[1], [2]])
print(Bm.shape)
Bm

In [ ]:
Bv = np.array([1, 2])
print(Bv.shape)
Bv

In [ ]:
np.dot(A, Bm)

In [ ]:
np.dot(A, Bv)

## Sum/Addition

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)

In [35]:
print(A.sum())       # sum all the elements
print(A.sum(axis=0)) # sum rows
print(A.sum(axis=1)) # sum columns

1.462035090114843
[1.46203509]
[ 0.69572502  0.12944343  0.4599395   0.86507704 -0.6881499 ]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4]])

print(a.shape)
print(b.shape)

sum_a = np.sum(a)
sum_b = np.sum(b)
print(sum_a.shape)
print(sum_b.shape)

sum_a_keep = np.sum(a, keepdims=True)
sum_b_keep = np.sum(b, keepdims=True)
print(sum_a_keep.shape)
print(sum_b_keep.shape)

In [ ]:
print(A + 100)
print()
B = np.array([[100, 200, 300]])
print(A + B)

## Vectorization vs for-loop

In [ ]:
import time

# w and x are 1 million array
w = np.random.rand(1000000)
x = np.random.rand(1000000)

tic = time.time()
c = np.dot(w, x)
toc = time.time()
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    c += w[i] * x[i]
toc = time.time()
print("for-loop version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    pass
toc = time.time()
print("for-loop pass version: " + str(1000*(toc-tic)) + "ms")
print(c)
