# Numpy Notes

In [28]:
import numpy as np
import pandas as pd

## np array shape

In [29]:
A3 = np.array([1, 2, 3])
A1x3 = np.array([[1, 2, 3]])
print(A3.shape)
print(A1x3.shape)

(3,)
(1, 3)


In [48]:
# a is a rank 1 array
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))
print(np.dot(a.T, a))
a = a.reshape((5, 1))
print(a)
print()

# A is a column vector (5x1)
A = np.random.randn(5, 1)
print(A)
print(A.shape)
# A.T is a row vector (1x5)
print(A.T)
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[ 0.92451248 -1.09142647  1.43091762  1.53374373  0.49812304]
(5,)
[ 0.92451248 -1.09142647  1.43091762  1.53374373  0.49812304]
6.693956680112251
6.693956680112251
[[ 0.92451248]
 [-1.09142647]
 [ 1.43091762]
 [ 1.53374373]
 [ 0.49812304]]

[[-1.42299844]
 [ 0.7232463 ]
 [ 1.65171761]
 [-0.09490481]
 [-0.98559921]]
(5, 1)
[[-1.42299844  0.7232463   1.65171761 -0.09490481 -0.98559921]]
[[ 2.02492457 -1.02917836 -2.35039159  0.1350494   1.40250614]
 [-1.02917836  0.52308521  1.19459866 -0.06863956 -0.71283099]
 [-2.35039159  1.19459866  2.72817106 -0.15675595 -1.62793158]
 [ 0.1350494  -0.06863956 -0.15675595  0.00900692  0.09353811]
 [ 1.40250614 -0.71283099 -1.62793158  0.09353811  0.97140581]]
[[6.25659358]]


## eye and identity matrix

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [519]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [520]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [521]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [522]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Load txt data

In [523]:
data = np.loadtxt("ex1data1.txt",delimiter=',')

In [524]:
data[:5]

array([[ 6.1101, 17.592 ],
       [ 5.5277,  9.1302],
       [ 8.5186, 13.662 ],
       [ 7.0032, 11.854 ],
       [ 5.8598,  6.8233]])

In [525]:
X = data[:, 0]
y = data[:, 1]

In [526]:
X[:5], y[:5]

(array([6.1101, 5.5277, 8.5186, 7.0032, 5.8598]),
 array([17.592 ,  9.1302, 13.662 , 11.854 ,  6.8233]))

In [527]:
m = len(X)
m

97

# Binding arrays

## Bind two or more 1-dimentional arrays as a matrix

In [56]:
a = np.array([1, 2, 3])
b = np.ones(3)

In [57]:
print(a.shape)
a

(3,)


array([1, 2, 3])

In [58]:
print(b.shape)
b

(3,)


array([1., 1., 1.])

In [531]:
c = np.zeros(3)
m = np.column_stack((c, b, a))

In [532]:
print(m.shape)
m

(3, 3)


array([[0., 1., 1.],
       [0., 1., 2.],
       [0., 1., 3.]])

In [25]:
np.dstack((c, b, a))

NameError: name 'c' is not defined

In [534]:
np.vstack((c,b,a))

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 2., 3.]])

In [535]:
np.stack((c, b, a))

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 2., 3.]])

In [536]:
np.hstack((c, b, a))

array([0., 0., 0., 1., 1., 1., 1., 2., 3.])

In [537]:
np.concatenate((c, b, a))

array([0., 0., 0., 1., 1., 1., 1., 2., 3.])

In [538]:
np.append(b, a)

array([1., 1., 1., 1., 2., 3.])

In [539]:
np.append(b, a, axis=0)

array([1., 1., 1., 1., 2., 3.])

## Reshape and flatten matrices

In [540]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [541]:
a.flatten('C')

array([1, 2, 3, 4, 5, 6])

In [542]:
a.flatten('F')

array([1, 4, 2, 5, 3, 6])

In [543]:
a.flatten('A')

array([1, 2, 3, 4, 5, 6])

In [544]:
a.flatten('K')

array([1, 2, 3, 4, 5, 6])

In [545]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

A3x2 B2x1

In [556]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [547]:
Bm = np.array([[1], [2]])
print(Bm.shape)
Bm

(2, 1)


array([[1],
       [2]])

In [548]:
Bv = np.array([1, 2])
print(Bv.shape)
Bv

(2,)


array([1, 2])

In [549]:
np.dot(A, Bm)

array([[ 5],
       [11],
       [17]])

In [550]:
np.dot(A, Bv)

array([ 5, 11, 17])

## Sum/Addition

In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
print(A.sum())       # sum all the elements
print(A.sum(axis=0)) # sum rows
print(A.sum(axis=1)) # sum columns

21
[5 7 9]
[ 6 15]


In [26]:
print(A + 100)
print()
B = np.array([[100, 200, 300]])
print(A + B)

[[101 102 103]
 [104 105 106]]

[[101 202 303]
 [104 205 306]]


## Vectorization vs for-loop

In [69]:
import time

# w and x are 1 million array
w = np.random.rand(1000000)
x = np.random.rand(1000000)

tic = time.time()
c = np.dot(w, x)
toc = time.time()
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    c += w[i] * x[i]
toc = time.time()
print("for-loop version: " + str(1000*(toc-tic)) + "ms")
print(c)

c = 0
tic = time.time()
for i in range(1000000):
    pass
toc = time.time()
print("for-loop pass version: " + str(1000*(toc-tic)) + "ms")
print(c)


Vectorized version: 1.5981197357177734ms
249900.97619657166
for-loop version: 549.0961074829102ms
249900.97619657393
for-loop pass version: 56.91790580749512ms
0
