# Numpy Notes

In [516]:
import numpy as np
import pandas as pd

## np array

In [517]:
np.array([1, 2, 3])

array([1, 2, 3])

## eye and identity matrix

In [518]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [519]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [520]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [521]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [522]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Load txt data

In [523]:
data = np.loadtxt("ex1data1.txt",delimiter=',')

In [524]:
data[:5]

array([[ 6.1101, 17.592 ],
       [ 5.5277,  9.1302],
       [ 8.5186, 13.662 ],
       [ 7.0032, 11.854 ],
       [ 5.8598,  6.8233]])

In [525]:
X = data[:, 0]
y = data[:, 1]

In [526]:
X[:5], y[:5]

(array([6.1101, 5.5277, 8.5186, 7.0032, 5.8598]),
 array([17.592 ,  9.1302, 13.662 , 11.854 ,  6.8233]))

In [527]:
m = len(X)
m

97

# Binding arrays

## Bind two or more 1-dimentional arrays as a matrix

In [528]:
a = np.array([1, 2, 3])
b = np.ones(3)

In [529]:
print(a.shape)
a

(3,)


array([1, 2, 3])

In [530]:
print(b.shape)
b

(3,)


array([1., 1., 1.])

In [531]:
c = np.zeros(3)
m = np.column_stack((c, b, a))

In [532]:
print(m.shape)
m

(3, 3)


array([[0., 1., 1.],
       [0., 1., 2.],
       [0., 1., 3.]])

In [533]:
np.dstack((c, b, a))


array([[[0., 1., 1.],
        [0., 1., 2.],
        [0., 1., 3.]]])

In [534]:
np.vstack((c,b,a))

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 2., 3.]])

In [535]:
np.stack((c, b, a))

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 2., 3.]])

In [536]:
np.hstack((c, b, a))

array([0., 0., 0., 1., 1., 1., 1., 2., 3.])

In [537]:
np.concatenate((c, b, a))

array([0., 0., 0., 1., 1., 1., 1., 2., 3.])

In [538]:
np.append(b, a)

array([1., 1., 1., 1., 2., 3.])

In [539]:
np.append(b, a, axis=0)

array([1., 1., 1., 1., 2., 3.])

## Reshape and flatten matrices

In [540]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [541]:
a.flatten('C')

array([1, 2, 3, 4, 5, 6])

In [542]:
a.flatten('F')

array([1, 4, 2, 5, 3, 6])

In [543]:
a.flatten('A')

array([1, 2, 3, 4, 5, 6])

In [544]:
a.flatten('K')

array([1, 2, 3, 4, 5, 6])

In [545]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

A3x2 B2x1

In [556]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [547]:
Bm = np.array([[1], [2]])
print(Bm.shape)
Bm

(2, 1)


array([[1],
       [2]])

In [548]:
Bv = np.array([1, 2])
print(Bv.shape)
Bv

(2,)


array([1, 2])

In [549]:
np.dot(A, Bm)

array([[ 5],
       [11],
       [17]])

In [550]:
np.dot(A, Bv)

array([ 5, 11, 17])

In [1]:
def sayHi(name):
    print("Hi " + name)

sayHi("Angela")

Hi Angela


In [2]:
sayHi("Aadya")

Hi Aadya


In [3]:
sayHi('Mrs.Carter!')

Hi Mrs.Carter!


In [4]:
sayHi("Mme Glenn!")

Hi Mme Glenn!
